name = "easynews-cloudflare-worker"
compatibility_date = "2024-09-23"

compatibility_flags = ["nodejs_compat", "nodejs_compat_populate_process_env"]

[observability]
enabled = true
head_sampling_rate = 1 

[vars]
PORT = "1337"
EASYNEWS_LOG_LEVEL = "info"
EASYNEWS_SUMMARIZE_LOGS = "true"
CLOUDFLARE = "true"
CACHE_TTL = "6"
TOTAL_MAX_RESULTS = "500"
MAX_PAGES = "10"
MAX_RESULTS_PER_PAGE = "250"
